### ISSUE TITLE
似乎无法测试IPv6节点？

### ISSUE THREAD

**Issue by Utaea** [faceair/clash-speedtest#10]
测试条件是节点域名仅有AAAA记录，这种情况下会直接测速失败，如果在 https://github.com/faceair/clash-speedtest/blob/6df057b2e3eb95d53b840c292451f4e303e8a224/main.go#L253 的 if 语句块加上 fmt.Println(err) 会输出域名无法解析为 IPv6 地址，错误为 no such host，不先贴出更多信息了，想先问问作者是否有测试过IPv6节点是否能测速？因为我自行有修改过代码，如果可以，那么就是我的问题我自查代码，如果作者也发现无法测速，可能是代码出现了问题？

**Comment by sxueck** [comment]
你可以使用最新代码再次进行尝试（我这边没有ipv6测速环境），目前修改了url的提取方式，应该是可以的

**Comment by faceair** [comment]
我没有测过，内核应该是支持的，你可以检查下你的 DNS 是否可以正常解析 IPV6 地址。
