### ISSUE TITLE
可以支持 Meta 内核的配置文件或者订阅链接吗？

### ISSUE THREAD

**Issue by Stanley-baby** [faceair/clash-speedtest#18]
可以支持 Meta 内核的配置文件或者订阅链接吗？

**Comment by faceair** [comment]
可以支持，最新版用的 meta 内核了

**Comment by Stanley-baby** [comment]
请问哪里下载最新版呢？我看还是1.3.0版本呀

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: faceair ***@***.***>
发送时间: Thursday, October 5, 2023 6:57:51 PM
收件人: faceair/clash-speedtest ***@***.***>
抄送: Stanley-baby ***@***.***>; Author ***@***.***>
主题: Re: [faceair/clash-speedtest] 可以支持 Meta 内核的配置文件或者订阅链接吗？ (Issue #18)


可以支持，最新版用的 meta 内核了

―

**Comment by faceair** [comment]
刚才在走自动构建，现在有了 https://github.com/faceair/clash-speedtest/releases/tag/v1.4.0

**Comment by Stanley-baby** [comment]
好哒   谢谢大佬   我回去试试🙏

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: faceair ***@***.***>
发送时间: Thursday, October 5, 2023 7:02:45 PM
收件人: faceair/clash-speedtest ***@***.***>
抄送: Stanley-baby ***@***.***>; Author ***@***.***>
主题: Re: [faceair/clash-speedtest] 可以支持 Meta 内核的配置文件或者订阅链接吗？ (Issue #18)


刚才在走自动构建，现在有了 https://github.com/faceair/clash-speedtest/releases/tag/v1.4.0

**Comment by Stanley-baby** [comment]
大佬  好像还是不支持vless的节点，噫呜呜噫，跪求解决，噫呜呜噫………

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: faceair ***@***.***>
发送时间: Thursday, October 5, 2023 7:02:45 PM
收件人: faceair/clash-speedtest ***@***.***>
抄送: Stanley-baby ***@***.***>; Author ***@***.***>
主题: Re: [faceair/clash-speedtest] 可以支持 Meta 内核的配置文件或者订阅链接吗？ (Issue #18)


刚才在走自动构建，现在有了 https://github.com/faceair/clash-speedtest/releases/tag/v1.4.0

―
