### ISSUE TITLE
yaml文件存在异常字符导致退出程序

### ISSUE THREAD

**Issue by FGWong** [faceair/clash-speedtest#19]
yaml文件 出现下列字符必须转义 
:, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, `
并且出现控制字符，需要使用引号将其包含。
buf中的字符若存在异常，yaml.Unmarshal(buf, rawCfg); err != nil ，将会导致 直接退出程序，能否处理一下。

**Comment by faceair** [comment]
不能正确读取的话程序不能继续做什么啊，不退出后续也没法测速。

yaml 不正确的话 clash 也没法工作吧？

**Comment by FGWong** [comment]
> 不能正确读取的话程序不能继续做什么啊，不退出后续也没法测速。
> 
> yaml 不正确的话 clash 也没法工作吧？

是的，这样处理很正确。因为有很多个节点，只有个别节点信息存在非法字符，如果要是逐个节点读入和解析，抛弃出错的节点，其他节点还有可能有效。

**Comment by faceair** [comment]
这块暂时不处理了
