### ISSUE TITLE
win10 21H2 19044.2846 下 无法运行

### ISSUE THREAD

**Issue by LvChao1229** [faceair/clash-speedtest#2]
您好，解压后，运行exe程序闪屏一下，然后找不到程序打开的位置

**Comment by HaoTian22** [comment]
请正确使用程序，使用命令行添加正确参数才可以正常运行
如`./clash-speedtest -c 'https://example.com'`
（截图于Win11 22624.1690）
![image](https://user-images.githubusercontent.com/48882584/236620556-02d9a79b-c7ed-4c55-bc80-2af02531dca6.png)

**Comment by LvChao1229** [comment]
谢谢，会用了！已点赞！

**Comment by 873589028** [comment]
请问具体应该怎么操作
