### ISSUE TITLE
执行命令时报错：文件名、目录名或卷标语法不正确

### ISSUE THREAD

**Issue by Effrontery** [faceair/clash-speedtest#23]
具体报错内容如下
D:\Clash for Windows\clash-speedtest_Windows_x86_64>clash-speedtest -c '（订阅地址）' -f 'V2'
time="（当前时间）" level=warning msg="failed to read config: open '（订阅地址）': The filename, directory name, or volume label syntax is incorrect."

我进入测速工具包的cmd.exe，clash-speedtest -h的运行是正常的，但是对订阅地址的测速是失败的，下图是输出结果
<img width="862" alt="屏幕截图 2023-10-31 233732" src="https://github.com/faceair/clash-speedtest/assets/64764218/baf5cdcb-c58d-4ae3-b606-17eefb3e4dbd">

**Comment by HK115** [comment]
我也是

**Comment by faceair** [comment]
无法复现，再检查下大小写、额外的空格之类的吧
