### ISSUE TITLE
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+

### ISSUE THREAD

**Issue by Stanley-baby** [faceair/clash-speedtest#24]
### 显示一个警告⚠️
![CleanShot 2023-11-10 at 12 38 44@2x](https://github.com/faceair/clash-speedtest/assets/58399659/b7eed689-8f98-4ef0-82b4-ad82ca3c7b2c)

**Comment by faceair** [comment]
新版本已禁用 warn 日志。
