### ISSUE TITLE
Windows怎么用，搞不来一点点

### ISSUE THREAD

**Issue by Gillian-ye** [faceair/clash-speedtest#25]
Windows怎么用，搞不来一点点

**Comment by corgy-w** [comment]
一样的用法吧

**Comment by holore** [comment]
用cmd在clash-speedtest.exe所在的文件夹中输入命令行：clash-speedtest -c 1703551929300.yaml -f "HK|港"

**Comment by holore** [comment]
![image](https://github.com/faceair/clash-speedtest/assets/57315840/e8e18efb-40c7-4057-bd2d-2fe3133819d9)
