### ISSUE TITLE
只能测下载速度 无法测网站打开速度

### ISSUE THREAD

**Issue by 36bian** [faceair/clash-speedtest#28]
使用`clash-speedtest -c "path/config.xml" -l "google.com"`没有任何结果
单纯使用`clash-speedtest -c "path/config.xml"正常显示

但是我不需要测下载速度，没有意义。我只想知道想访问的域名，哪个节点打开快，目前程序不支持。

**Comment by wj6019** [comment]
嗯，赞同，可否自定义只测延迟或只测下载

**Comment by faceair** [comment]
不支持，只有这个程序目的就是测下载速度的，测节点带宽的。
