### ISSUE TITLE
一直报一个错误

### ISSUE THREAD

**Issue by yangkile** [faceair/clash-speedtest#3]
time="2023-05-09T10:12:20+08:00" level=fatal msg="Failed to load config: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `c3M6Ly9...` into main.RawConfig"

**Comment by faceair** [comment]
你似乎是贴了一个 ss 或者 ssr 的订阅过来了。
大部分的机场现在应该都是直接提供 clash 的订阅的链接的，如果没有找到的话也可以自己在 URL 后面加一下 &flag=clash 或者 &clash=1 看看。你可以先将修改后的 URL 贴到浏览器地址栏，看看下载回来的文件内容是否是人可以阅读的 yaml 文件，如果是一堆加密数据 (base64 编码) 那么就是订阅地址搞错了。

**Comment by yangkile** [comment]
我这家提供商clash链接也就是base64,转换后就纯ss链接排列了,纯ss地址,一行一个...这种好像也还挺多的,可以支持一下吧?

**Comment by faceair** [comment]
可以吧，我有空的时候整一下

**Comment by faceair** [comment]
https://sub.pet/ 你可以试试这种订阅转换的服务么？

**Comment by faceair** [comment]
预期可以通过各类订阅转换的服务来实现，除了上面这个域名也可以自行搜索其他的服务并自担风险，我这边暂不添加订阅转换的功能了。
