### ISSUE TITLE
大佬提一个需求，套socks5落地测速

### ISSUE THREAD

**Issue by irezm** [faceair/clash-speedtest#31]
某些服务买了原生IP，比如PayPal，但是原生IP速度会很慢或者被墙，于是需要机场加速，因为是买的socks5或者http代理，无法自己搭建测速工具，现在都是手动找出能用连通的节点，但是速度又回慢，希望能增加一个socks5或者http落地代理测速

**Comment by faceair** [comment]
https://clash.wiki/configuration/outbound.html#socks5

是支持的，你自己写好 clash 的配置文件就可以测试。
