### ISSUE TITLE
更换测速节点的方式

### ISSUE THREAD

**Issue by tdsq369** [faceair/clash-speedtest#33]
希望可以添加任何连接的下载测速 这样会使得这一切变的简单
 而不是使用speed.cloudflare.com/__down 变量类的 这太复杂了 有些地区对这些支持也不够友好

**Comment by faceair** [comment]
需要下载大文件才能测出节点的带宽，只靠浏览网页是不够的。
cloudflare 是国际知名的 CDN 厂商，线路已经是最优的了，如果你实在有什么需求可以自建测速服务器。
