### ISSUE TITLE
偶发性的一个小问题，不清楚到底是什么原因

### ISSUE THREAD

**Issue by WishMelz** [faceair/clash-speedtest#5]
测速选了一个最快的，延迟最低的。使用发现不行，youtu都打不开。我换到别的节点就可以，切换回来又不行。clash默认端口全局代理，浏览器用的SwitchyOmega。 具体什么问题不清楚，说一下这个问题。希望作者留意一下

**Comment by faceair** [comment]
当前测速使用的是 speed.cloudflare.com 这个域名，可以理解为测试是到代理节点到这个域名的网速。
如果实在是代理节点到 youtube 之间有啥毛病的话，不太好测试，也没法穷举这类情况，我这边可能无能为力了。

如果这个问题长期存在，可以咨询下机场那边，或者如果是自建节点可以上机器检查一下，如果是怀疑 clash 本身有啥毛病的话可以给 clash 那边提个 issue。

**Comment by anjue39** [comment]
> “可以理解为测试是到代理节点到这个域名的网速
这句话的意思是本地到代理节点再到这个域名的网速，还是仅指代理节点到这个域名的网速？

**Comment by faceair** [comment]
是双向的，本次经过代理节点从 speed.cloudflare.com 网站下载的速度
