### ISSUE TITLE
可以直接web网页筛选吗

### ISSUE THREAD

**Issue by anjue39** [faceair/clash-speedtest#7]
能直接导入，指定导入文件的地址生成吗。如果有个单独的配置文件，可以指定source来源，下载速度阈值，测试地址就好了

**Comment by anjue39** [comment]
优化建议：
1.增加一个下载速度的阈值的自定义声明。
2.导入的订阅链接先下载订阅文件到缓存，读取，然后运行程序进行筛选，
3.筛选出大于等于这个阈值的节点，最终把符合大于等于下载速度阈值的缺点留下，
同时节点命名改为节点名+下载速度。
4.最后的结果回写到订阅文件，clash其他策略等配置保持原来的，
5.最后保存到clash.yaml中，而不是按我提供的代码写入到csv中，修改一下。
6.最后运行一个workflow actions脚本,名字是clash.yml，运行程序，保存结果上传到clash.yaml。每次运行脚本自动覆盖上次的clash.yaml。

**Comment by faceair** [comment]
我的本意其实是测出来这个机场的大部分节点在高峰期行不行就够了，机场总体都不太行就换。

不用于判断机场内某些节点的质量，因为单个机场同一个区域的不同节点在大部分时候质量差异都不大。可能因为一些抖动会在测试的时候会有少许质量差异，但总体是趋同的。

如果你真的需要根据质量差异来决定用哪些节点的话，你可以提需求给 clash 项目，让他们在 url-test (测延迟) 之外再新增一个侧带宽的类型，这个在 clash 项目中来做会更方便。

**Comment by anjue39** [comment]
感谢回复！了解到你的本意和出发点了。只是看了代码后总觉得还差一点点就完美了，结果其实都缓存到了csv文件可，其实写到一个比如result.yaml文件可能更便捷，节点下载速度都有了，且有排序，稍加一个比如下载速度的阈值，就可以有一个筛选的结果。都支持订阅格式了，一开始完全可以先读取出来，rule策略等配置不变，筛选后的节点结果直接回填到原读取下来的订阅文件，指定路径保存成clash.yaml格式，就是一个更优质的订阅文件。以上又都可以弄个action脚本，弄个workflow文件，就可以做到。你看，其实这样更好。只是我也这样做了，搞了好几天，也不知道哪代码有问题，总搞不定。所以发了isuure把想法反馈给你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: faceair ***@***.***&gt;
发送时间: 2023年5月31日 09:29
收件人: faceair/clash-speedtest ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [faceair/clash-speedtest] 可以直接web网页筛选吗 (Issue #7)





 
我的本意其实是测出来这个机场的大部分节点在高峰期行不行就够了，机场总体都不太行就换。
 
不用于判断机场内某些节点的质量，因为单个机场同一个区域的不同节点在大部分时候质量差异都不大。可能因为一些抖动会在测试的时候会有少许质量差异，但总体是趋同的。
 
如果你真的需要根据质量差异来决定用哪些节点的话，你可以提需求给 clash 项目，让他们在 url-test (测延迟) 之外再新增一个侧带宽的类型，这个在 clash 项目中来做会更方便。

**Comment by anjue39** [comment]
我查看了github二十多个clash内核的speedest的源程序，还是觉得你这个测速原理靠谱，且最精简，只是需要得打命令需要客户端，没做到自动生成到文件，所以还是忍不住给你写了这些建议，用action最终生成一个.txt或者yaml文件比较方便



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: faceair ***@***.***&gt;
发送时间: 2023年5月31日 09:29
收件人: faceair/clash-speedtest ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [faceair/clash-speedtest] 可以直接web网页筛选吗 (Issue #7)





 
我的本意其实是测出来这个机场的大部分节点在高峰期行不行就够了，机场总体都不太行就换。
 
不用于判断机场内某些节点的质量，因为单个机场同一个区域的不同节点在大部分时候质量差异都不大。可能因为一些抖动会在测试的时候会有少许质量差异，但总体是趋同的。
 
如果你真的需要根据质量差异来决定用哪些节点的话，你可以提需求给 clash 项目，让他们在 url-test (测延迟) 之外再新增一个侧带宽的类型，这个在 clash 项目中来做会更方便。

**Comment by anjue39** [comment]
至于你说的可以反馈给clash项目。不多想，他们能做早做了，想加上早加上了。没戏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: faceair ***@***.***&gt;
发送时间: 2023年5月31日 09:29
收件人: faceair/clash-speedtest ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [faceair/clash-speedtest] 可以直接web网页筛选吗 (Issue #7)





 
我的本意其实是测出来这个机场的大部分节点在高峰期行不行就够了，机场总体都不太行就换。
 
不用于判断机场内某些节点的质量，因为单个机场同一个区域的不同节点在大部分时候质量差异都不大。可能因为一些抖动会在测试的时候会有少许质量差异，但总体是趋同的。
 
如果你真的需要根据质量差异来决定用哪些节点的话，你可以提需求给 clash 项目，让他们在 url-test (测延迟) 之外再新增一个侧带宽的类型，这个在 clash 项目中来做会更方便。

**Comment by faceair** [comment]
收到，我考虑一下看怎么实现吧

**Comment by anjue39** [comment]
终于说动你了！诚然，如我所说，稍微完善，真的更好！我其实搞了好几天，我把你代码里有用的配置都放到了./config/config.yaml文件自定义，main.go做调用，用workflow脚本运行，还是卡在哪里了

**Comment by anjue39** [comment]
这是我提交给chatpgt的需求，抛转引玉，供你参考
```
把下面代码做如下修改：
1.增加一个下载速度的阈值的自定义声明。
2.导入的订阅链接先下载订阅文件到缓存，读取，然后运行程序进行筛选，
3.先对订阅链接里的代理列表进行带宽和延迟测速，保存到result.yaml文件
3.筛选出大于等于这个阈值的节点，最终把符合大于等于下载速度阈值的缺点留下，
同时节点命名改为节点名+下载速度。例如：节点8|6.5Mb/s
4.最后的结果回写到订阅文件，clash其他策略等配置保持原来的，当然如果能自定义一个rule.ini配合筛选后的代理生成一个新订阅文件更好
5.最后保存到clash.yaml中，而不是写入到缓存csv中，修改一下。
6.最后建立一个workflow actions脚本,名字是make_clash.yml，运行程序，保存结果push上传到clash.yaml。
建立一个workflow actions脚本,名字是make_result.yml，运行程序，保存测速节点带宽延迟结果到result.yaml，push上传
每次运行脚本自动覆盖上次。
```

**Comment by anjue39** [comment]
但能力有限，抛砖引玉
1.能自定义的单独弄个config文件，这样比较清晰，
![image](https://github.com/faceair/clash-speedtest/assets/98279987/1686ddb5-a920-46c2-aa13-18bc464ce7bd)
![image](https://github.com/faceair/clash-speedtest/assets/98279987/dbd165f0-4828-44a5-a72d-86dec6707e24)
![image](https://github.com/faceair/clash-speedtest/assets/98279987/d157f7d3-d356-497e-bf7c-f43e945ca785)

**Comment by Stanley-baby** [comment]
希望可以支持Meta 核心，这样就可以支持vless 节点了。🙏🏻

**Comment by anjue39** [comment]
测试命令可以在web网页或者workflow里实现吗？可以增加一个下载速度阈值的设定吗？以更好地筛选

**Comment by anjue39** [comment]
> 能力有限，文件架构图供参考
> 
> 1.能自定义的单独弄个config文件，这样比较清晰，
> 
> ![image](https://github.com/faceair/clash-speedtest/assets/98279987/1686ddb5-a920-46c2-aa13-18bc464ce7bd)
> 
> ![image](https://github.com/faceair/clash-speedtest/assets/98279987/dbd165f0-4828-44a5-a72d-86dec6707e24)
> 
> ![image](https://github.com/faceair/clash-speedtest/assets/98279987/d157f7d3-d356-497e-bf7c-f43e945ca785)
> 
> 
> 
> 

归拢到一个配置config文件，架构会更清晰，承载本程序所有自定义配置
