### ISSUE TITLE
speed.cloudflare.com/__down这个接口有替换/备选方案吗

### ISSUE THREAD

**Issue by wangyongheng97** [faceair/clash-speedtest#8]
有的机场订阅会屏蔽[https://speed.cloudflare.com/](https://speed.cloudflare.com/)网站，无法发送数据进行测速。有类似的网站可以替代吗？我进行了一些搜索，但没有找到合适的方案，不知道作者熟不熟悉这方面，还请指点。

**Comment by faceair** [comment]
现在已支持自建测速服务器。
